steps:
  - id: "Build"
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:$BUILD_ID", "."]

  - id: "Push"
    name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}:$BUILD_ID"]

  - id: "Terraform"
    name: "hashicorp/terraform:1.8.4"
    dir: "terraform"
    entrypoint: "/bin/sh"
    args:
      - "-c"
      - |
        terraform init -input=false
        terraform apply -auto-approve \
          -var "project_id=$PROJECT_ID" \
          -var "region=${_REGION}" \
          -var "image_name=${_IMAGE}" \
          -var "service_account_email=${_SERVICE_ACCOUNT}"

substitutions:
  _REGION: "us-central1"            # TODO(cloud): change if you pick a different region
  _REPO: "autorc-docker"
  _IMAGE: "autoresearcher"
  _SERVICE_ACCOUNT: "<YOUR-SA>@${PROJECT_ID}.iam.gserviceaccount.com"  # TODO(cloud): real SA email

images:
  - "${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_REPO}/${_IMAGE}"
