steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/autoresearcher', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/autoresearcher']
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'autoresearcher'
      - '--image'
      - 'gcr.io/$PROJECT_ID/autoresearcher'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
